// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArse6zomwnxGKSOqsZhIde51yn_7moCw0',
    appId: '1:960487896050:web:d21bada721ef32a191b16b',
    messagingSenderId: '960487896050',
    projectId: 'macrotrackermobile-eeb3e',
    authDomain: 'macrotrackermobile-eeb3e.firebaseapp.com',
    storageBucket: 'macrotrackermobile-eeb3e.firebasestorage.app',
    measurementId: 'G-BWCS8K4Q0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyIsf5G0p0PI3gSW0MI17ioBAnJXjxtE',
    appId: '1:960487896050:android:977c1e80fa887aed91b16b',
    messagingSenderId: '960487896050',
    projectId: 'macrotrackermobile-eeb3e',
    storageBucket: 'macrotrackermobile-eeb3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvIVKKLlXBXyvShnz9jt6TmOdT7v2OfEk',
    appId: '1:960487896050:ios:c56d9fea970140cd91b16b',
    messagingSenderId: '960487896050',
    projectId: 'macrotrackermobile-eeb3e',
    storageBucket: 'macrotrackermobile-eeb3e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvIVKKLlXBXyvShnz9jt6TmOdT7v2OfEk',
    appId: '1:960487896050:ios:c56d9fea970140cd91b16b',
    messagingSenderId: '960487896050',
    projectId: 'macrotrackermobile-eeb3e',
    storageBucket: 'macrotrackermobile-eeb3e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArse6zomwnxGKSOqsZhIde51yn_7moCw0',
    appId: '1:960487896050:web:e0aa7074d5e0529491b16b',
    messagingSenderId: '960487896050',
    projectId: 'macrotrackermobile-eeb3e',
    authDomain: 'macrotrackermobile-eeb3e.firebaseapp.com',
    storageBucket: 'macrotrackermobile-eeb3e.firebasestorage.app',
    measurementId: 'G-LEW551T6EB',
  );
}
